# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-14 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_auto_20190214_0610'),
        ('buy', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(max_length=50, verbose_name='车辆名称')),
                ('regist_date', models.DateField(verbose_name='上牌日期')),
                ('engineNo', models.CharField(max_length=50, verbose_name='发动机号')),
                ('mileage', models.IntegerField(default=0, verbose_name='公里数')),
                ('maintenance_record', models.TextField(verbose_name='维修记录')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='期望售价')),
                ('extreactprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格')),
                ('newprice', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='新车价格')),
                ('picture', models.ImageField(default='normal.png', upload_to='img/car', verbose_name='图片')),
                ('debt', models.CharField(choices=[('无', '无债务'), ('有', '待处理债务')], default='无', max_length=20, verbose_name='债务')),
                ('other', models.TextField(verbose_name='第三方评估')),
                ('promise', models.TextField(verbose_name='卖家承诺')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Brand')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.Order')),
            ],
        ),
    ]
